export const darkTheme = {
  color: "#ffffff",
  bgColor: "#141517",
  boxShadow: "none",
  border: "1px solid #505050",
  navbarli: "#d4d7db",
  mainWrapper: "#000",
  h1Wrapper: "#fff",
  MovieDetailSpan: "rgb(186, 186, 193)",
  movieDetailOutline: "1px solid black",
  ContentSelectBar: "black",
  swiperColor: "black",
  origin: "white",
  originBlack: "black",
  movieChart: "linear-gradient(to bottom, #000, rgb(255 255 255 / 80%))",
};

export const lightTheme = {
  color: "#000000",
  bgColor: "#f9f9fd",
  boxShadow: "0 0 10px -3px #a0a0a0",
  border: "none",
  navbarli: "black",
  mainWrapper: "#fff",
  h1Wrapper: "#000",
  MovieDetailSpan: "black",
  movieDetailOutline: "1px solid white",
  ContentSelectBar: "white",
  swiperColor: "white",
  orgin: "black",
  originBlack: "white",
  movieChart: "linear-gradient(to bottom,rgb(255 255 255 /80%), #000, rgb(255 255 255 / 80%))",
};
